### ISSUE TITLE
Graph larger than GPU VRAM

### ISSUE THREAD

**Issue by archenroot** [LuxGraph/Lux#2]
Just to check how Lux is implemented. i would like to test scenarios with potentially 1-10 billions of nodes and same number of relationships in multiple scenarios in range from dense graph to sparse graph. Does Lux support iteration over grahp storage CPU<->GPU in case my graph is larger than GPU VRAM?

**Comment by jiazhihao** [comment]
Lux can distribute your graph representation across multiple GPUs on a single or multiple machines. That being said, Lux requires the aggregated VRAM across all GPUs is larger than graph data, and will use the aggregated VRAM to store graph data.

**Comment by archenroot** [comment]
@jiazhihao - Thx for explanation. I will do initial test on 8x P100 gpu node, later on cluster.

Do you recommend any kind of specific interconnect (10g,56G,100G?) between nodes? I mean from perspective, where the higher throughput doesn't add much additional performance. something like from 10G to 56G you gain 100% in overall performance in distributed mode, but on 56G to 100g you gain only 30%, it means that building 100G network is less effective.

I of course also understand that when such GPU units with 64/128/256 and more VRAM will come to market, there will be already PCIE 4.0 in place and potentially new NVLink, which will require even higher interconnects...

Thanks for this works. I started also studying a bit the Legion, I like that so far :-)

**Comment by jiazhihao** [comment]
@archenroot Sorry that I missed your previous message.

My experience is that most graph analytics benchmarks (e.g., PageRank, SSSP) are communication bound, in which case improving interconnect helps. However, if you try to run some compute intense ML/DL applications, improving interconnect may not help you.

Feel free to let us know if you have any question about Lux/Legion. For Legion, we have a user mailing list legionusers@googlegroups.com

**Comment by archenroot** [comment]
@jiazhihao - thank you very much for your answer, and thanks again for your cool work :-)
