### ISSUE TITLE
A problem about BFS implementation

### ISSUE THREAD

**Issue by JsonZhangAA** [LuxGraph/Lux#4]
Hello,
       I am very interested in Lux.But I have a question.
       Why not implement BFS?

**Comment by jiazhihao** [comment]
Thank you for your interests in Lux. A BFS implementation would be very similar to our SSSP example. You can simply change the `atomicMin` operation in SSSP to `atomicCAS` to get a reasonable BFS implementation.

**Comment by JsonZhangAA** [comment]
Thanks for your reply!
